---
# Uses the same Ruby style rules as Rotom.
# Copy this file to your app root as .rubocop.yml
#
# Change ruby-3.3 to ruby-3.2 if you use Ruby 3.2

inherit_gem:
  standard: config/ruby-3.4.yml

AllCops:
  Exclude:
    - "db/schema.rb"